### PR TITLE
add browser info to onshow callback

### PR DESCRIPTION
**Pull request by joshkg**
Reference: https://github.com/browser-update/browser-update/issues/470

### CODE REVIEW

**Comment by josselex** [comment]
I'll have a look at it tomorrow.

**Comment by peter-mouland** [comment]
hey, this would be cool, anything we can do to help?

**Comment by joshkg** [comment]
@peter-mouland Hi! Author asked for a tweak on this PR which I haven't had a chance to do yet, will try to get to it today!

**Comment by joshkg** [comment]
@josselex updated with your recommendation to move browser info into the `op` object!

**Comment by tomheaps** [comment]
@joshkg @josselex please can one of you explain how you obtain the browser info for use in the onshow callback. I see it was added as a pull request and reported as a new feature in the last blog post (below) but I can't find any info on what the option is in the docs?

image

**Comment by joshkg** [comment]
@tomheaps the argument you have available in the callback is `options` and you can find browser details on the `browser` property like `options.browser`

**Comment by tomheaps** [comment]
@joshkg Thanks for replying. Got it working now but it would be good if the docs were updated to make this clearer... the argument used in the example for the `onshow` callback was `infos`:

image

**Comment by joshkg** [comment]
@tomheaps Yep a note in the docs would be a good thing, maybe @josselex can help with that. Of course you could name your argument `bananas` and it'd work, just an arg name 😉

**Pull request closed without merging**
