### PR TITLE
added global arabic locale

### PR DESCRIPTION
**Pull request by ArabCoders**
Hello

this pull request add support for global Arabic locale, however i'm unsure how to support multiple locales such as (ar_KW/ar_SA/ar_OM etc as they are pretty much the same there is no difference in Arabic writing in all the major arabic countries.

we probably could add check for ar_* and map it to ar_AR. that's what [1] facebook does as well

[1] https://developers.facebook.com/docs/internationalization

### CODE REVIEW

**Comment by josselex** [comment]
Thanks a lot! Arabic was still missing! This is great.

I uploaded it and it can be found online: 
http://browser-update.org/ar/update.html

However, one sentence is not translated as you can see.
Can you fix this?
All Arabic locales ar_* are now mapped to ar_EG (it hat to be a valid locale to work).

**Comment by ArabCoders** [comment]
Thanks i've sent another pull request to merge in the missing one #243

**Comment by ArabCoders** [comment]
@josselex BTW Arabic string is not showing up in update.js or update.min.js yet. i thought it might be a build thing, but it's almost two months now ^^

**Comment by josselex** [comment]
Sorry. I forgot to add it there. Now its online.

**Comment by ArabCoders** [comment]
Thank you

**Pull request merged**
