### PR TITLE
Updated the default url location such that one can pass in url rather than always as default

### PR DESCRIPTION
**Pull request by sbha5516**
Updated the default url location such that one can pass in url rather than always as default

To pass in, use in the client site js
```
 url: "yoururl" 
```
I adde this
```
this.op.url =op.url ||  "http://browser-update.org/update-browser.html";
```

### CODE REVIEW

**Comment by josselex** [comment]
This is already possible. See line 33 of https://github.com/browser-update/browser-update/blob/master/update.js

**Comment by josselex** [comment]
I've documented in commit 5d8921b

**Comment by sbha5516** [comment]
Thanks. However, I also added clearer icons for you at https://github.com/sbha5516/browser-update/commit/d4bb9d4696e6e17c1ac04cd6d8b1271e8c8639c5 . May you add that to the code so that we can get clearer more transparent browser images. Thanks

**Comment by josselex** [comment]
Yes. Sure! Could you create a new pull request for that?

2015-06-25 3:18 GMT+02:00 sbha5516 <notifications@github.com>:

**Pull request closed without merging**
